apiVersion: v1
kind: Service
metadata:
  name: http-service
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: proxy
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.100.21
