apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: osm2pgsql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: osm2pgsql
    spec:
      containers:
      - name: osm2pgsql
        image: osmtw/osm2pgsql:0.88.1
        env:
        - name: PG_ENV_POSTGRES_USER
          value: "postgres"
        - name: PG_ENV_POSTGRES_DB
          value: "postgres"
        - name: PG_ENV_POSTGRES_PASSWORD
          value: "pa55w0rd"
        - name: PG_PORT_5432_TCP_ADDR
          value: "postgis"
        - name: PG_PORT_5432_TCP_PORT
          value: "5432"
        volumeMounts:
        - name: osm
          mountPath: "/osm"
      volumes:
      - name: osm
        emptyDir: {}
