apiVersion: v1
kind: Service
metadata:
  name: postgis
  labels:
    app: postgis
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
      - name: postgis
        image: osmtw/postgis
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "pa55w0rd"
        volumeMounts:
        - name: osmdb
          mountPath: "/var/lib/postgresql/data"
        ports:
        - containerPort: 5432
      volumes:
      - name: osmdb
        emptyDir: {}
