apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: proxy
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: nginx:mainline
        env:
        - name: NGINX_PORT
          value: "80"
        volumeMounts:
        - name: nginx
          mountPath: "/etc/nginx/"
        ports:
        - containerPort: 80
      volumes:
      - name: nginx
        hostPath:
          path: /home/rancher/osm-tiles-docker/nginx/
